= Tackler PDF Reports

[NOTE]
====
This is under development feature of Tackler
====

This folder contains link:https://github.com/typst/typst[Typst] templates
for Tackler reports.

The data folder has example reports in text and json format and `report-bal.typ`
is currently proof-of-concept, prototype Typst report for the balance report.

If you would like to contribute for default report templates, that would be highly appreciated.

== How to generate PDF reports

You will need link:https://github.com/typst/typst[Typst] tool, then run:

----
typst compile report-bal.typ
----


== Documentation

* Tackler Examples: link:https://github.com/tackler-ng/tackler/tree/main/examples#readme[In this repo, under examples]
* Tackler Documentation: link:https://tackler.fi/docs/[Tackler's site]

=== Documentation for Reports

* link:https://tackler.fi/docs/tackler/latest/reports/report-balance/[Balance Report]
* link:https://tackler.fi/docs/tackler/latest/reports/report-balance-group/[Balance Group Report]
* link:https://tackler.fi/docs/tackler/latest/reports/report-register/[Register Report]

== Test data

Tackler has support for JSON output, it can be activated with configuration setting:

----
[report]
formats = [ "txt", "json" ]
----

or using CLI argument `--formats txt json`.

Reports must be generated with file output
(`--output.dir path/to/output` and `--output.prefix filename`),
this will generate JSON output alongside TXT format.

Tackler's
link:https://github.com/tackler-ng/tackler-tests[test suite] contains many more report examples.

=== Examples

Tackler https://github.com/tackler-ng/tackler/tree/main/examples#audit-and-account-auditing-setup[Audit]
(journal audit data) and https://github.com/tackler-ng/tackler/tree/main/examples#commodity-prices[Mapple]
(commodity prices) examples have JSON output activated already.
