= Tackler performance test setup

This directory contains tools and reference results for Tackler's performance testing.

See link:https://tackler.fi/docs/tackler/latest/features/performance/[Description of Performance]
for explanation of generated artificial test data.

It is recommemded to put the perf data directory outside of Tackler project directory.  
If 1E5-1E6 data sets are inside project's directory, your IDE might go nuts while it scans new files.


== Results

Tools to run perf tests are located in link:./bin[bin].

* xref:./results/perf-hw02.adoc[HW02 results]


== Test data

Test data is generated with 
link:https://github.com/tackler-ng/pta-generator[generator tool]


File count of test sets:
----
$ for ds in perf-1E?; do echo -n "$ds: "; find $ds -type f | wc -l; done
set-1e1: 10
set-1e2: 100
set-1e3: 1000
set-1e4: 10000
set-1e5: 100000
set-1e6: 1000000
----

Actual data size of test sets:
----
$ for ds in perf-1E?; do echo -n "$ds: "; (find $ds -type f | xargs cat ) | wc -c; done
set-1e1:       1_358
set-1e2:      13_664
set-1e3:     137_598
set-1e4:   1_385_945
set-1e5:  13_959_367
set-1e6: 140_587_889
----

Size on disk for test sets:
----
set-1e1    128K
set-1e2    856K
set-1e3    5.4M
set-1e4     41M
set-1e5    398M
set-1e6    3.9G
----

=== Git perf test repository

Size of bare test data repository: 201M


== Possible layout for perf test data

Content of `perf-test` directory, next to the `tackler`'s toplevel directory:

----
bin 		   	-> ../tackler-ng/perf/bin/
perf.toml 	   	-> ../tackler-ng/perf/perf.toml
results 	   	-> ../tackler-ng/perf/results/
data 			== perf data
----

