= Tackler Examples

See tackler
link:https://tackler.fi/docs/tackler/latest/examples/[ Documentation and Examples]
for longer explanation of these examples.


These examples are supposed to be run from project root folder after you have
built a release version of tackler:

----
# with just
just release-build

# with cargo
cargo build --release --bin tackler
----

== Create a new Journal Setup

----
target/release/tackler new journal
target/release/tackler --config journal/conf/tackler.toml
----


== Simple Journal

Example of simple journal setup:

----
target/release/tackler --config examples/simple.toml
----


== Audit and Account Auditing Setup

To run this example, make sure that you have cloned the
repository with submodules. If not, run first:

----
git submodule init
git submodule update
----

And then:

----
target/release/tackler --config examples/audit.toml
----

Audit test data has a branch with 100_000 transactions, this query will execute in few seconds:

----
target/release/tackler \
   --config examples/audit.toml \
   --input.git.ref set-1e5 \
   --accounts 'a:ay2016:am12'
----

Structure of the test data is described in Tackler's 
link:https://tackler.fi/docs/tackler/latest/features/performance/#test-data[Performance Test] 
documentation.

== Transaction filters

Filter definition as plain JSON:

----
target/release/tackler \
    --config examples/audit.toml \
    --input.git.ref set-1e2 \
    --reports register \
    --accounts 'a:.*' \
    --audit.mode true \
    --api-filter-def \
      '{ "txnFilter": { "TxnFilterTxnDescription": { "regex": "1E2 txn-(1|17|100)" }}}'
----

Same filter with base64 armor:

----
target/release/tackler \
    --config examples/audit.toml \
    --input.git.ref set-1e2 \
    --reports register \
    --accounts 'a:.*' \
    --audit.mode true \
    --api-filter-def \
      base64:eyAidHhuRmlsdGVyIjogeyAiVHhuRmlsdGVyVHhuRGVzY3JpcHRpb24iOiB7ICJyZWdleCI6ICJeMUUyIHR4bi0oMXwxN3wxMDApJCIgfX19Cg==
----


== Commodity Prices

These are a set of examples to demonstrate link:https://tackler.fi/docs/tackler/latest/commodities/price/[commodity price functionalities].

=== Current Market Value

The full example is on Tackler's site: link:https://tackler.fi/docs/tackler/latest/commodities/price/current-market-value/[Current Market value]


----
target/release/tackler \
    --config examples/maple.toml \
    --reports balance \
    --accounts "Assets:Coins" \
    --price.lookup-type last-price \
    --report.commodity CAD
----

=== Historic Market Value

The full example is on Tackler's site: link:https://tackler.fi/docs/tackler/latest/commodities/price/historic-market-value/[Historic Market value]

----
target/release/tackler \
    --config examples/maple.toml \
    --reports balance \
    --accounts "Assets:Coins" \
    --price.lookup-type given-time \
    --price.before 2024-03-01 \
    --report.commodity CAD
----

=== Solar Energy Examples

The full example is on Tackler's site: link:https://tackler.fi/docs/tackler/latest/examples/solar-energy-value/[Solar Energy Value]

==== Value of the energy when used at the site

----
target/release/tackler \
   --config examples/solar.toml \
   --reports balance
----

==== Value of the Energy if sold to the grid

----
target/release/tackler \
   --config examples/solar.toml \
   --reports balance \
   --pricedb examples/solar/txns/se-sold.db
----
