= TEP-1018: External reference ID

Add new External Id (`ext-id`) metadata field to transactions.

ref: link:https://github.com/tackler-ng/tackler/issues/141[GH Issue 141]

== Description

The external reference id (ext-id) is meant to connect transaction data to external source,
and optionally enforce uniqueness of that over the transaction set.

Main use case is to connect information between external systems with tackler journal,
for example when importing CVS records to tackler.
The uniqueness feature could be used to prevent importing same records twice.

It would be then up to the import logic how this would be unique,
it could be a checksum over the CVS row data,
or if the external source have own ids, that could be used.

The only restriction for content of the ext-id is, that it can't be empty,
and it must consist Unicode characters (it can't be control characters).

== Summary of Changes

Summary of planned changes:

* Journal format: This is new journal format feature, and it's backward compatible
* Engine
** New field in various data model objects
** Support txn ext-id with filtering
* conf: provide toggle to enforce uniqueness


== Journal File Format

New transaction metadata item:

`ext-id`:: non-empty, single line, newline terminated, trimmed (begin, end) string


== Implementation

Detailed implementation planning

=== CLI Changes

No changes to the command line interface with initial implementation.

See also future plans for use case xref:use-case-lookup[lookup].

=== CONF Changes

Changes to conf-settings

* [x] new configuration table `kernel.ext-id`
** [x] option to enforce uniqueness `kernel.ext-id.unique = <true | false>`
** [ ] _future_: option to enforce existence of `ext-id` `kernel.ext-id.mandatory = <true | false>`

==== Tackler `init` / `new` commands

Changes to tackler `new` or `init` commands

* [x] Add the ext-id section, with `unique = false`


=== Filtering Changes

Changes to filtering logic or implementation

* [x] new regex-based txn property filter for `ext-id`

[source, json]
----
{
  "TxnFilterTxnExtId" : {
    "regex" : "<regex>"
  }
}
----


=== Tackler Core Engine

Changes to the tackler core engine (e.g. core implementation)


==== API Changes

Api changes to server or client interfaces.

===== Server API Changes

No changes to Server API

===== Client API Changes

No changes to client API

===== JSON Model

Changes to JSON model

* Metadata: no changes to report's metadata section
* [x] JSON Reports
** BalanceReport: no changes
** BalanceGroupReport: no changes
** [x] RegisterReport
*** [x] new metadata field `extId`


==== New Dependencies

No new dependencies


=== Reporting

Changes to reports or reporting

==== Balance Report

No changes to the balance report.

==== Balance Group Report

No changes to the balance group report.

==== Register Report

Changes to register report

* [x] new metadata field
    txt:: `# ext-id: ...`
    json:: `extId`


=== Exporting

Changes to exports or exporting

==== Equity Export

No changes to the equity export.

==== Identity Export

Changes to identity export

* [x] new metadata field `ext-id`

==== Accounts Export

No changes to the accounts export.


=== Documentation

* [x] xref:./readme.adoc[]: Update TEP index
* [x] link:../../CHANGELOG[]: add new item
* [x] Does it warrant own T3DB file?
** [x] update T3DB: README.adoc
** [x] update xref:../../suite/check-tests.sh[]
** [x] Add new T3DB file link:https://github.com/tackler-ng/tackler-t3db/[tests-XXXX.yml: TEP-XXXX T3DB]
* [x] User docs
** [x] User Manual
*** cli-arguments: No changes
** [x] tackler.toml
*** [x] `kernel.ext-id.unique`


=== Future Plans and Postponed (PP) Features

Changes to conf-settings

* [ ] configuration table `kernel.ext-id`
** [ ] _future_: option to enforce existence of ext-id
      `kernel.ext-id.mandatory = <true | false>`


[[use-case-lookup]]
==== Use case: test for existence

New tackler command family `lookup` with arguments:
* `lookup ext-id <id> ...`
* `lookup uuid <uuid> ...`

These will print raw transaction(s) with matching `ext-id` and `uuid`.
The implementation would be basically just `TxnFilter` -> `Identity export` to `stdout`.
The return value should indicate if there was a match.

There should be also global flag `-q` / `--quit` to suppress the output,
and just test the existence of the txn with particular `ext-id` and `uuid`


==== Postponed (PP) Features

Anything which wasn't implemented?


=== Tests

Normal, ok-case tests to validate functionality:

* [x] basic functionality
* [x] filtering: `ext-id`
* [x] txn without ext-id are allowed
* [x] identity test: txn -> identity -> register report
* [x] `ext-id.unique`
** [x] `unique = false`: same ids are fine

Update:

* [x] // test: b88d6733-2acf-4021-a3d7-deaf58b518a6
      // desc: "reject invalid metadata constructions"
* [x] // test: 5bb95c2e-2fad-4584-9380-e6cafe732cf6
      // desc: "accepts multiple metadata items"


==== Errors

Various error cases:

* [x] e: empty ext-id
* [x] e: `ext-id.unique`
** [x] e: `unique = true`: same ids cause error


==== Perf

Is there need to run or create new perf tests?

* [x] perf: `tackler-core/benches/parser_bench.rs`
** [x] perf test: `metadata`
** [x] perf test: `everything`

==== Feature and Test Coverage Tracking

Feature-id::

* name: External reference id
* uuid: 4e5f753f-d124-45e9-b703-6e2a588d3e85

link:https://github.com/tackler-ng/tackler-t3db/[tests-XXXX.yml: TEP-XXXX T3DB]


==== Metadata template for Feature and Test Coverage Tracking

....
features:
  - feature:
      id: 4e5f753f-d124-45e9-b703-6e2a588d3e85
      subject: "external reference id"

  - feature:
      id: 33282cc5-f722-49e4-9f58-c5ff519d18d3
      parent: 4e5f753f-d124-45e9-b703-6e2a588d3e85
      subject: "ext-id basic functionality"

  - feature:
      id: 9798c6d8-b07a-47ac-a463-e2e729c39fa6
      parent: 4e5f753f-d124-45e9-b703-6e2a588d3e85
      subject: "ext-id filters"

  - feature:
      id: 35f8b046-86b6-4acf-9442-437ec150664b
      parent: 4e5f753f-d124-45e9-b703-6e2a588d3e85
      subject: "kernel.ext-id.unique"
....


'''
Tackler is distributed on an *"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND*, either express or implied.
See the link:../../LICENSE[License] for the specific language governing permissions and limitations under
the link:../../LICENSE[License].
